# -*- coding: utf-8 -*-
"""ENGAssignment5.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LJp_S89DBZG2kueot04aDVBC165seaJw
"""

# Commented out IPython magic to ensure Python compatibility.
# # Step 1: Install required libraries
# !pip install streamlit pyngrok
# 
# # Step 2: Write Streamlit app to a file
# %%writefile app.py
# import streamlit as st
# 
# # Create a simple Streamlit app
# st.title('Hello World App')
# st.write('This is a simple Streamlit app running in Google Colab!')
# 
# # Step 3: Set up Ngrok and launch the app
# from pyngrok import ngrok
# 
# # Kill any existing tunnels
# ngrok.kill()
# 
# # Create a new ngrok tunnel
# public_url = ngrok.connect(port='8501')
# print(f'Public URL: {public_url}')
# 
# # Run the Streamlit app
# !streamlit run app.py &>/dev/null &
#