# -*- coding: utf-8 -*-
"""ENGAssignment5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1geHPXGULEjaCg1FdFHsAi5Swm9kAqXbM
"""

# app.py

import streamlit as st

# Create a simple app
st.title('Hello World App')
st.write('This is a simple Streamlit app saying Hello World!')