# -*- coding: utf-8 -*-
"""ENGAssignment5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1geHPXGULEjaCg1FdFHsAi5Swm9kAqXbM
"""

# app.py

import streamlit as st

# Title of the app
st.title('Hello World App')

# Add input for user name
name = st.text_input("Enter your name", placeholder="Type your name here")

# Add a slider to adjust the font size
font_size = st.slider('Choose the font size for your greeting', 10, 100, 30)

# Display the greeting message when the user enters their name
if name:
    st.markdown(f"<h1 style='font-size:{font_size}px;'>Hello, {name}!</h1>", unsafe_allow_html=True)
else:
    st.write("Please enter your name to see a personalized greeting.")